In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
import joblib

In [5]:
a = pd.read_csv("marks.csv")
a

name  hrs  marks
0   vimal    7     70
1  rahul     5     50
2   eric     8     80
3   harry    2     20

In [6]:
a.values

array([['vimal', 7, 70],
       ['rahul ', 5, 50],
       ['eric ', 8, 80],
       ['harry', 2, 20]], dtype=object)

In [7]:
type(a)

pandas.core.frame.DataFrame

In [8]:
#feature / Independent variable
x=a['hrs']
x

0    7
1    5
2    8
3    2
Name: hrs, dtype: int64

In [9]:
x.shape

(4,)

In [11]:
type(x)

pandas.core.series.Series

In [12]:
x=x.values

In [13]:
type(x)

numpy.ndarray

In [14]:
x=x.reshape(4,1)

In [15]:
x.shape

(4, 1)

In [16]:
x

array([[7],
       [5],
       [8],
       [2]], dtype=int64)

In [18]:
y=a['marks']
y

0    70
1    50
2    80
3    20
Name: marks, dtype: int64

In [19]:
y.values

array([70, 50, 80, 20], dtype=int64)

In [20]:
y.shape

(4,)

In [21]:
type(y)

pandas.core.series.Series

In [22]:
y=y.values

In [23]:
type(y)

numpy.ndarray

In [24]:
y=y.reshape(4,1)

In [25]:
y.shape

(4, 1)

In [26]:
y

array([[70],
       [50],
       [80],
       [20]], dtype=int64)

In [27]:
mind = LinearRegression()

In [28]:
#Exp : Model : Linear function
#w : weight/coefficient
#model trained
mind.fit(x,y)

LinearRegression()

In [29]:
mind.predict([[6]])

array([[60.]])

In [30]:
joblib.dump(mind,'marks.pk1')

['marks.pk1']

In [31]:
#======================load it==========================

In [32]:
mind=joblib.load('marks.pk1')

In [33]:
mind.predict([[9]])

array([[90.]])